### ISSUE TITLE
would you like to share your search code?

### ISSUE THREAD

**Issue by meteorshowers** [lmb-freiburg/autodispnet#1]
Great work!
would you like to share your search code?

**Comment by tonmoy-saikia** [comment]
Hi, sorry we are unable to release the search code due to dependencies with some private libraries (related to data reading). But the first order DARTS implementation should be simple to implement. You could implement the optimization step as follows:

```
arch_opt = tf.train.AdamOptimizer(learning_rate=3e-4, beta1=0.5, beta2=0.999) 
weight_opt = tf.train.MomentumOptimizer(learning_rate=0.025, momentum=0.9)
train_avg_grad_vars = ... # tuple containing gradients and variables on the train set
val_avg_grad_vars = ...   # tuple containing gradients and variables on the val set

# loss op for weight parameters
train_loss = tf.reduce_mean(tf.get_collection('epe_loss_weights'), name='train_loss')    
# loss op for architecture parameters (alphas) 
val_loss = tf.reduce_mean(tf.get_collection('epe_loss_architecture'), name='val_loss') 
# Run ops in sequence:
with tf.control_dependencies(update_ops): 
    arch_train_op = arch_opt.apply_gradients(val_avg_grad_vars)
    with tf.control_dependencies([arch_train_op]):
        weight_train_op = weight_opt.apply_gradients(train_avg_grad_vars, global_step=global_step)
```

**Comment by meteorshowers** [comment]
Thanks!
Is it hard to not use lmbspecialops and netdef_slim. to realized the autodisp?

**Comment by meteorshowers** [comment]
Another question is can the autodisp search the channel of convolution?
Thanks a lot!

**Comment by tonmoy-saikia** [comment]
> Thanks!
> Is it hard to not use lmbspecialops and netdef_slim. to realized the autodisp?

You need lmbspecialops for the correlation layer. 
The current codebase has minimal dependencies with netdef_slim. 

>Another question is can the autodisp search the channel of convolution?

It searches for operations in a block/cell structure.
